import fs from 'fs'
import path from 'path'

import { IBowtieResult } from './interfaces'

/**
 * Parse bowtie-raw.jsonl (output of `bowtie suite`) into compliance summaries.
 * Each line is one of:
 *   - header line: { implementations, bowtie_version, dialect, ... }
 *   - case line:   { seq, case: { description, schema, tests } }
 *   - result line: { seq, implementation, expected, results }      ← normal
 *   - error line:  { seq, implementation, expected, errored, ... } ← whole case errored
 */
function parseBowtieJsonl(raw: string): IBowtieResult[] {
    const lines = raw.trim().split('\n').filter(Boolean)
    if (lines.length === 0) return getFallbackData()

    // First line is the header
    const header = JSON.parse(lines[0])
    if (!header.implementations) return getFallbackData()

    const implementations = Object.keys(header.implementations)
    const stats: Record<string, { passed: number; failed: number; errored: number }> = {}
    for (const impl of implementations) {
        stats[impl] = { passed: 0, failed: 0, errored: 0 }
    }

    for (let i = 1; i < lines.length; i++) {
        const item = JSON.parse(lines[i])

        // Skip case definition lines (no 'implementation' key)
        if (!('implementation' in item) || !('seq' in item)) continue

        const impl = item.implementation
        if (!stats[impl]) continue

        // Whole-case errored (e.g. strict mode rejecting unknown keyword)
        if (item.errored === true) {
            const count = Array.isArray(item.expected) ? item.expected.length : 0
            stats[impl].errored += count
            continue
        }

        // Normal result line
        const expected: boolean[] = item.expected ?? []
        const results: Array<{ valid?: boolean; errored?: boolean }> = item.results ?? []

        for (let j = 0; j < expected.length; j++) {
            const res = results[j]
            if (!res) continue
            if (res.errored) {
                stats[impl].errored++
            } else if (res.valid === expected[j]) {
                stats[impl].passed++
            } else {
                stats[impl].failed++
            }
        }
    }

    return implementations.map(impl => {
        const s = stats[impl]
        const total = s.passed + s.failed + s.errored
        const compliance = total > 0 ? Math.round((s.passed / total) * 10000) / 100 : 0
        const info = header.implementations[impl]
        return {
            implementation: impl,
            name: info.name ?? impl,
            language: info.language ?? 'unknown',
            version: info.version ?? 'unknown',
            dialect: 'draft2020-12',
            passed: s.passed,
            failed: s.failed,
            errored: s.errored,
            total,
            compliance,
        }
    })
}

export async function fetchBowtieCompliance(): Promise<IBowtieResult[]> {
    // Try real JSONL file first (generated by GitHub Actions)
    const jsonlPath = path.join(__dirname, '..', 'data', 'bowtie-raw.jsonl')
    if (fs.existsSync(jsonlPath)) {
        try {
            const raw = fs.readFileSync(jsonlPath, 'utf-8')
            const results = parseBowtieJsonl(raw)
            if (results.length > 0) return results
        } catch (e) {
            console.warn('Failed to parse bowtie-raw.jsonl, using fallback:', e)
        }
    }

    // Try pre-summarised JSON (bowtie summary --format json output)
    const jsonPath = path.join(__dirname, '..', 'data', 'bowtie-results.json')
    if (fs.existsSync(jsonPath)) {
        try {
            const json = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'))
            if (Array.isArray(json) && json.length > 0) return json
        } catch (e) {
            console.warn('Failed to parse bowtie-results.json, using fallback:', e)
        }
    }

    return getFallbackData()
}

function getFallbackData(): IBowtieResult[] {
    return [
        { implementation: 'python-jsonschema', name: 'jsonschema',          language: 'python',     version: '4.26.0', dialect: 'draft2020-12', passed: 1276, failed: 1,  errored: 0,   total: 1277, compliance: 99.92 },
        { implementation: 'js-hyperjump',      name: 'hyperjump-json-schema', language: 'javascript', version: '1.17.4', dialect: 'draft2020-12', passed: 1273, failed: 4,  errored: 0,   total: 1277, compliance: 99.69 },
        { implementation: 'js-ajv',            name: 'ajv',                  language: 'javascript', version: '8.18.0', dialect: 'draft2020-12', passed: 1029, failed: 27, errored: 221, total: 1277, compliance: 80.58 },
    ]
}