import fs from 'fs'
import path from 'path'
import { IBowtieResult } from './interfaces'

export async function fetchBowtieCompliance(): Promise<IBowtieResult[]> {
    console.log(`🎯 Loading Bowtie compliance data...`)

    const filePath = path.join(__dirname, '..', 'data', 'bowtie-results.json')

    // if file exists (generated by GitHub Actions) use it
    if (fs.existsSync(filePath)) {
        try {
            const raw = fs.readFileSync(filePath, 'utf-8')
            const json = JSON.parse(raw)
            const results = parseBowtieResults(json)
            console.log(`  ✅ Loaded ${results.length} implementations from bowtie-results.json`)
            return results
        } catch (e) {
            console.warn(`  ⚠️  Failed to parse bowtie-results.json: ${e instanceof Error ? e.message : String(e)}`)
        }
    }

    // fallback to curated data for local development
    console.log(`  ℹ️  bowtie-results.json not found — using curated fallback data`)
    console.log(`  ℹ️  Run GitHub Actions workflow to get real Bowtie data`)
    return getFallbackData()
}

function parseBowtieResults(json: any): IBowtieResult[] {
    // bowtie summary --format json structure
    const implementations = json.implementations ?? {}

    return Object.entries(implementations)
        .map(([id, impl]: any) => {
            const counts = impl.counts ?? {}
            const passed  = counts.passed  ?? 0
            const failed  = counts.failed  ?? 0
            const errored = counts.errored ?? 0
            const skipped = counts.skipped ?? 0
            const total   = passed + failed + errored + skipped || 1

            return {
                implementation: impl.name ?? id,
                language: impl.language ?? 'unknown',
                passed,
                failed,
                errored,
                skipped,
                total,
                compliance: Math.round((passed / total) * 1000) / 10
            }
        })
        .sort((a, b) => b.compliance - a.compliance)
}

function getFallbackData(): IBowtieResult[] {
    const raw = [
        { implementation: 'ajv',           language: 'javascript', passed: 862, failed: 6,   errored: 0, skipped: 0 },
        { implementation: 'hyperjump',     language: 'javascript', passed: 858, failed: 10,  errored: 0, skipped: 0 },
        { implementation: 'json-everything', language: 'dotnet',   passed: 856, failed: 12,  errored: 0, skipped: 0 },
        { implementation: 'jsonschema',    language: 'python',     passed: 851, failed: 17,  errored: 0, skipped: 0 },
        { implementation: 'networknt',     language: 'java',       passed: 840, failed: 28,  errored: 0, skipped: 0 },
        { implementation: 'rapidjson',     language: 'cpp',        passed: 790, failed: 78,  errored: 0, skipped: 0 },
    ]
    return raw.map(r => {
        const total = r.passed + r.failed + r.errored + r.skipped || 1
        return { ...r, total, compliance: Math.round((r.passed / total) * 1000) / 10 }
    })
}