import fs from 'fs';
import path from 'path';
import { fetchJson } from './helper/helper';
import { INpmDownloadStatsResponse } from './interfaces';
import { fetchBowtieCompliance } from './bowtie';



async function fetchNpmDownloads(packageName: string) {
    const url = `https://api.npmjs.org/downloads/range/last-week/${packageName}`

    try {
        const data = await fetchJson<INpmDownloadStatsResponse>(url)
        const totalDownloads = data.downloads.reduce((sum, day) => {
            return sum + day.downloads
        }, 0)

        console.log(`✅ ${packageName}: ${totalDownloads} downloads last week`)

        return {
            package: packageName,
            totalDownloads,
            dailyDownloads: data.downloads
        }
    } catch (e) {
        throw new Error(`Failed to fetch npm downloads for ${packageName}: ${e instanceof Error ? e.message : String(e)}`)
    }
}


async function main() {
    console.log("📦 Fetching npm download stats...")

    const packages = [
        "ajv",
        "jsonschema",
        "z-schema",
        "tv4",
        "ajv-formats",
    ]

    const results = []

    for (const pkg of packages) {
        try {
            const stats = await fetchNpmDownloads(pkg)
            results.push(stats)
        } catch (e) {
            console.error(`Failed to fetch stats for ${pkg}: ${e instanceof Error ? e.message : String(e)}`)
        }
    }

    const bowtieResults = await fetchBowtieCompliance()

    const snapshot = {
    collectedAt: new Date().toISOString(),
    npm_downloads: results,
    bowtie_compliance: {
        dialect: 'draft2020-12',
        note: 'Real data generated by Bowtie GitHub Action in CI. Fallback used for local development.',
        results: bowtieResults
    }
}

    const date = new Date().toISOString().slice(0, 10)

    const historyPath = path.join(__dirname, '..', 'data', `snapshot-${date}.json`)
    const latest = path.join(__dirname, '..', 'data', `snapshot-latest.json`)

    
    fs.mkdirSync(path.dirname(historyPath), {recursive: true})
    fs.writeFileSync(historyPath, JSON.stringify(snapshot, null, 2))
    fs.writeFileSync(latest, JSON.stringify(snapshot, null, 2))
    console.log(`💾 Snapshot saved to ${historyPath}`)
}

main().catch(e => {
    console.error(`Unexpected error: ${e instanceof Error ? e.message : String(e)}`)
    process.exit(1)
})

